[package]
name = "regex-syntax"
version = "0.1.0"  #:version
authors = ["The Rust Project Developers", "Andrew Gallant <jamslam@gmail.com>", "Pablo Lanza <pablolanza89@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A regular expression parser."
workspace = ".."
edition = "2021"
